setwd("C:\\R\\Test\\Hospital")
outcome <- read.csv("outcome-of-care-measures.csv",colClasses = "character")
head(outcome)
names(outcome)
ncol(outcome)
nrow(outcome)
outcome[,11] <- as.numeric(outcome[,11])
hist(outcome[,11])
